bcbk5/bcbk5/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^regis/', include('registration.urls')),
    url(r'^session/', include('schedule.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('rest_framework_docs.urls'))
)

bcbk5/registration/urls.py
from django.conf.urls import patterns, include, url
from registration.views import RegistrationView

urlpatterns = patterns('',
	url(r'^$', RegistrationView.as_view(), name='registration')
)

bcbk5/schedule/urls.py
from django.conf.urls import patterns, include, url
from django.views.decorators.clickjacking import xframe_options_exempt

from schedule.views import SessionView, SessionRenderView

urlpatterns = patterns('',
	url(r'^$', SessionView.as_view(), name='session'),
	url(r'^render$', xframe_options_exempt(SessionRenderView.as_view()), name='session_table')
)

bcbk5/schedule/models.py
from django.db import models
from django.core.exceptions import ValidationError

ROOMS = (
	(0, '17201'),
	(1, '17302'),
	(2, '17303'),
	(3, '17304'),
	(4, '17401'),
	(5, '17402'),
)
TIMESLOT = (
	(10, '10:40 - 11:10'),
	(20, '11:10 - 11:40'),
	(30, '11:40 - 12:10'),
	(40, '13:00 - 13:30'),
	(50, '13:30 - 14:00'),
	(60, '14:00 - 14:30'),
	(70, '14:30 - 15:00'),
	(80, '15:20 - 15:50'),
	(90, '15:50 - 16:20'),
	(100, '16:20 - 16:50'),
)

class Session(models.Model):
	name = models.CharField(max_length=255)
	by = models.CharField(max_length=255)
	room = models.SmallIntegerField(choices=ROOMS)
	slot = models.SmallIntegerField(choices=TIMESLOT)
	double = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.name

	def get_time_start(self):
		return self.get_slot_display().split(' - ')[0]

	def get_time_end(self):
		if not self.double:
			return self.get_slot_display().split(' - ')[1]

		slot = [x[0] for x in TIMESLOT].index(self.slot)
		slot += 1

		return TIMESLOT[slot][1].split(' - ')[1]

	# def clean(self):
	# 	if self.double:
	# 		slot = [x[0] for x in TIMESLOT].index(self.slot)
	# 		if slot % 2 != 0:
	# 			raise ValidationError('Double sized session must fall on first of hour slot')

	class Meta:
		ordering = ['slot', 'room']

bcbk5/schedule/views.py
from django.conf import settings
from django.views.generic import ListView

from rest_framework import status
from rest_framework.response import Response
from rest_framework import generics

from schedule.models import Session, ROOMS, TIMESLOT
from schedule.serializers import SessionSerializer

class SessionView(generics.ListAPIView):
	"""
	List sessions.

	room -- tbd
	slot -- tbd
	double -- true for 1 hr session length
	"""
	queryset = Session.objects.all()
	serializer_class = SessionSerializer

class SessionRenderView(ListView):
	queryset = Session.objects.order_by('slot', 'room')
	template_name = 'schedule/timetable.html'
	context_object_name = 'sessions'

	def get_context_data(self, **kwargs):
		context = super(SessionRenderView, self).get_context_data(**kwargs)
		context['ROOMS'] = ROOMS
		context['TIMESLOT'] = TIMESLOT

		return context

bcbk5/schedule/templates/schedule/timetable.html
{% load static %}
{% load schedule_filter %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Session table</title>
	<link rel="stylesheet" type="text/css" href="http://2014.barcampbangkhen.org/css/sessiontable.css">
	<style>
body{
	margin: 0;
	padding: 0;
	font-family: helvetica, sans-serif;
}
	</style>
</head>
<body>
<div class="announce">
	Barcamp Bangkhen 5 Timetable
	<noscript>&mdash; Please enable JavaScript</noscript>
</div>
<ol class="sessionlist">
{% for session in sessions %}
	{% ifchanged session.slot %}
	{% if session.slot == 40 %}
	<li class="announce">
		12.10 - 13.00 :  Lunch
	</li>
	{% endif %}
	{% if session.slot == 80 %}
	<li class="announce">
		15.00 - 15.20 : Break
	</li>
	{% endif %}
	<li class="timesection">{{session.get_slot_display}}</li>
	{% endifchanged %}
	<li itemscope itemtype="http://schema.org/Event" class="session room-{{session.room}} {% if session.double %}double{% else %}single{% endif %}">
		<div class="room" itemprop="location">{{session.get_room_display}}</div>
		<div class="card">
			<div class="title" itemprop="name">{{session.name}}</div>
			<div class="time">
				<time itemprop="startDate">{{session.get_time_start}}</time> - 
				<time itemprop="endDate">{{session.get_time_end}}</time>
			</div>
			<div class="by" itemprop="performer">{{session.by}}</div>
		</div>
	</li>
{% endfor %}
</ol>
<table class="sessiontable">
	<thead>
		<tr>
			<th></th>
			{% for room in ROOMS %}
			<th>{{room.1}}</th>
			{% endfor %}
		</tr>
	</thead>
	<tbody>
		{% for time in TIMESLOT %}
		<tr>
			<td>{{time.1}}</td>
			{% for room in ROOMS %}
			{% for session in sessions|filter_slot:time.0|filter_room:room.0 %}
			{% if session.name %}
			<td itemscope itemtype="http://schema.org/Event" class="session {% if session.double %}double{% else %}single{% endif %}">
				<div class="session-in">
					<div class="title" itemprop="name">{{session.name}}</div>
					<div class="time">
						<time itemprop="startDate">{{session.get_time_start}}</time> - 
						<time itemprop="endDate">{{session.get_time_end}}</time>
					</div>
					<div class="by" itemprop="performer">{{session.by}}</div>
				</div>
			</td>
			{% endif %}
			{% empty %}
			<td></td>
			{% endfor %}
			{% endfor %}
		</tr>
		{% if time.0 == 30 %}
		<tr>
			<td>12.10 - 13.00</td>
			<td class="break" colspan="{{ROOMS|length}}">Lunch</td>
		</tr>
		{% endif %}
		{% if time.0 == 70 %}
		<tr>
			<td>15.00 - 15.20</td>
			<td class="break" colspan="{{ROOMS|length}}">Break</td>
		</tr>
		{% endif %}
		{% endfor %}
	</tbody>
</table>
</body>
</html>